config/routes.rb
Rails.application.routes.draw do
 
 resources :employees, except: [:new] do
 post '/message_choice', to: 'employees#message_choice' 
 post '/stop_request', to: 'employees#stop_request'
 resources :shifts do
 member do
 	post 'notify'
  post 'accept'
 end
end
end
get '/register', to: 'employees#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
get 'bulletin', to: 'shifts#index', as: :bulletin
############### Constraints for the top routes 
get '/acccounts', to: 'accounts#new', as: :sign_up
post '/accounts', to: 'accounts#create', as: :accounts



root to: 'dashboard#index', as: '/dashboard'


end

app/models/employee.rb
class Employee < ActiveRecord::Base
	belongs_to :account
  belongs_to :department
	has_many :shifts
	has_many :notifies
  has_many :employee_shifts
  has_many :shifts, through: :employee_shifts


  has_secure_password validations: false
	validates :username, presence: true, uniqueness: true
	validates :password, presence: true, on: :create
	validates :email, :email_format => {message: 'needs valid email format'}
  validate :authcode_matches

   def authcode_matches
   	unless self.authcode == 'c3p2ze'
   		errors.add(:authcode, "Incorrect authorization code")
   	end
   end 

   def set_flag(type) 
    self.flag = type
    self.save
   end 

   def set_alert(type)
    self.alert = type
    self.save
   end 
  

	 def full_name 
	 	f_name + " " + l_name
	 end



end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :require_employee, only: [:show]
	

	def index
		@employees = Employee.all
	end

	def new
		@employee = Employee.new
	end

	def create
		@employee = Employee.new(employee_params)
		#current_account.employees << Employee.new(employee_params)
		if @employee.save
			session[:employee_id] = @employee.id
			binding.pry
			flash[:success] = "Successfully Registered"
			redirect_to bulletin_path
		else
			flash[:danger] = "There is something wrong with your input"
			render :new
		end
	end

	def show
		@employee = @current_employee
		@shift = Shift.where(employee_id: @current_employee.id)
		@copyshifts = @shift.dup
	end

	def edit
	end

	def update

	end
	
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to root_path
	end


def message_choice
	@employee = current_employee
	@employee.set_flag(params[:flag])
	flash[:success] = "Your notification type has been set"
	redirect_to employee_path(session[:employee_id])
end

def stop_request
	@employee = current_employee
	@employee.set_alert(params[:choice])
	flash[:success] = "Your notifications will stop" 
	redirect_to employee_path(session[:employee_id])
end


	private

	def employee_params
		params.require(:employee).permit(:username, :f_name, :l_name, :email, :authcode, :password)
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.erb
<% @employees.each do |employee|%>
  <%= employee.f_name %>
<% end %>

app/views/employees/new.html.erb
<center>
<h1>Register</h1>
</center>
</hr>


<!-- Register Form  -->
</br> 
<% if @employee.errors.any?%>
<div>
<h3><%=pluralize(@employee.errors.count,' errors')%> 
Prohibited the Form from being sent:</h3>
<ul>
<% @employee.errors.full_messages.each do |message|%>
<li><%= message%></li>
<% end %>
</ul>
<% end%>
</div>
<%=form_for(@employee, url: employees_path) do |f| %>
<div class= "col-md-6 centered-form" >

<div class='form-group'>
<%=f.text_field :username, class: "ghost-input", placeholder: "Enter a Username"%>
</div>
<div class='form-group'>
<%=f.text_field :f_name, class: "ghost-input", placeholder: "Enter your First Name"%>
</div>
<div class='form-group'>
<%=f.text_field :l_name, class: "ghost-input", placeholder: "Enter your Last Name"%>
</div>
<div class='form-group'>
<%=f.text_field :email, class: "ghost-input", placeholder: "Enter your Email Address"%>
</div>
<div class="form-group"> 
<%=f.text_field :phone, class: "ghost-input", placeholder: "Phone Number"%>
</div>
<div class='form-group'>
<%=f.password_field :password, class: "ghost-input", placeholder: "I am a password field"%>
</div>
<div class='form-group'>
<%=f.text_field :authcode, class: "ghost-input", placeholder: "Enter your Authorization"%>
</div>
<%=f.submit ('Register'), class: "ghost-button" %>
<% end %>
</div>

app/views/employees/show.html.erb
<div class="container top">
<h1 class="profile-name text-center">Profile: <%=@employee.f_name.upcase%></h1>
<hr>
<%=link_to 'Back', employee_shifts_path(@employee), class: "btn btn-block btn-danger"%>
</br>
<%= link_to 'Add Shift', new_employee_shift_path(current_employee.id), class: "btn btn-block btn-primary"%>
</br>

	<div class='notify-hover'>
	<button class="btn btn-warning btn-block">Notification Type</button>
	</div>

	<div class="notify-container col-sm-12">
		<p> Notification Type: </p>
			<%=form_tag employee_message_choice_path(@employee), method: 'post' do %>
				<%if @employee.flag == 'email'%>
			<%= radio_button_tag 'flag', 'email', :checked => true %> Email
				<%else%>
			<%= radio_button_tag 'flag', 'email'%> Email
				<%end%>
				<%if @employee.flag == 'text_message'%>
			<%= radio_button_tag 'flag', 'text_message', :checked => true %> Text Message
				<%else%>
			<%= radio_button_tag 'flag', 'text_message'%> Text Message
				<%end%>
			<%= submit_tag 'Set' %>
				<%end%>
	</br>
		<p>Stop Notifications:</p>
		<%= form_tag employee_stop_request_path(@employee), method:'post' do %>
			<% if @employee.alert == 'yes' %>
		<%= radio_button_tag 'choice', 'yes', :checked => true %> Yes
			<% else %>
		<%= radio_button_tag 'choice', 'yes'%> Yes
			<%end%>
			<% if @employee.alert == 'no' %>
		<%= radio_button_tag 'choice', 'no', :checked => true %> No
			<% else %>
		<%= radio_button_tag 'choice', 'no'%> No
			<%end%>
		<%= submit_tag 'Set'%>
			<%end%>
	</div>
</br>
<div class='shift-hover'>
<button class="btn btn-success btn-block"> My Shifts</button>
</div>

<table class="table shift-container">
	<tr>
	<th>Date</th>
	<th>Position</th>
	<th>Remove</th>
	</tr>
		<% @shift.each do |shift|%>
	<tr> 
		<td><%=shift.shift_day.strftime("%b-%d")%></td>
        <td><%="#{shift.position}"%></td> 
        <td><%=link_to 'Remove', employee_shift_path(current_employee, shift.id) , method: :delete, data: { confirm: "Are you sure?" } %></td>
	</tr>
		<%end%>
</table>
</div>
<script>
$('.notify-hover').on('click', function(){
  $('.notify-container').toggle(1000);
});

$('.shift-hover').on('click', function(){
  $('.shift-container').toggle(1000);
});
</script>