config/routes.rb
Rails.application.routes.draw do
 
 resources :employees, except: [:new] do
 post '/message_choice', to: 'employees#message_choice' 
 post '/stop_request', to: 'employees#stop_request'
 resources :shifts do
 member do
 	post 'notify'
  post 'accept'
 end
end
end
get '/register', to: 'employees#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
get 'bulletin', to: 'shifts#index', as: :bulletin
############### Constraints for the top routes 
get '/acccounts', to: 'accounts#new', as: :sign_up
post '/accounts', to: 'accounts#create', as: :accounts



root to: 'dashboard#index', as: '/dashboard'


end

app/models/shift.rb
class Shift < ActiveRecord::Base
	belongs_to :employee
	has_many :notifies, as: :notifyable
  has_many :employee_shifts
  has_many :coworkers, through: :employee_shifts, class_name: 'Employee', foreign_key: 'coworker_id'

  require 'date'
  
def weeks(wkn)
  today = Date.today
  if wkn.to_i == 1
   week_1 = (today..today.end_of_week).to_a
   # all_days = (week_1.at_beginning_of_week..week_1.at_end_of_week).map
   return clean_week(week_1)
  elsif wkn.to_i == 2
   week_2  = today.next_week.tomorrow
   all_days = (week_2.at_beginning_of_week..week_2.at_end_of_week).map
   return clean_week(all_days.to_a)
  elsif wkn.to_i == 3
   week_3 = today.next_week.next_week.tomorrow
   all_days = (week_3.at_beginning_of_week..week_3.at_end_of_week).map
   return clean_week(all_days.to_a)
  elsif wkn.to_i == 4
    week_4 = today.next_week.next_week.next_week.tomorrow
    all_days = (week_4.at_beginning_of_week..week_4.at_end_of_week).map
   return  clean_week(all_days.to_a)
  end 
end

# reformat the date time
def clean_week(list)
  list.map!{|x| x.to_s}
end


def self.weeks_ranges
   today = Date.today
   current_week = "#{today} - #{today.end_of_week}"
    count = 0
    i = 7
    until count == 3
      "#{today.next_week + count*i} - #{today.end_of_week + count*i}"
      count += 1
    end
end



  

# def self.get_days(wkn, desired_days)
#   week = Shift.weeks(wkn)
#   get_days = week.select do |x|
#     desired_days.any? { |day| x.send(day + '?') }
#   end 
# end

def self.get_days_week(wkn, desired_days)
  week_days = self.weeks(wkn)
  selected_days = week_days.select!{|x| desired_days.include? x.strftime('%A')}
  favorite_days = selected_days.map!{|x|x.strftime('%Y/%m/%d')}
  db_shifts =self.where(:shift_day => favorite_days)
end



end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
	include ShiftsHelper
	before_action :check_if_allowed, only: [:notify]

def index
	# paginate(:page => params[:page], :per_page => 5)
	# @shift = Employee.where(id: session[:employee_id]).take
	@shifts = Shift.all.paginate(:page => params[:page], :per_page => 2)
	@new_instance = Shift.new
	if params[:week]
	@container = @new_instance.weeks(params[:week])
	end
	if params[:day]
	@shifts = Shift.find_by_sql(["SELECT * FROM shifts WHERE shift_day = ?", params[:day] ]).paginate(:page => params[:page], :per_page => 10 )
	end
end

def show
@employee = current_employee
@shift = @employee.shifts.find(params[:id])
@wants = @shift.coworkers
end

def new
@employee = current_employee
@shift = Shift.new
end

def create
@shift = Shift.new(shift_params)
 if @shift.save!
 	@shift.employee_id = current_employee.id
 	@shift.save
 	flash[:success] = "New shift was added"
	redirect_to employee_shifts_path
  else
	flash[:danger] = "Shift was not added"
	render 'new'
 end
end

def destroy
	@employee = current_employee
	@shift = @employee.shifts.find(params[:id])
	@shift.destroy
	redirect_to employee_shifts_path
end

def notify
	@user = current_employee
	@shift = Shift.find(params[:id])
	if @shift.coworkers <<  @user
		if current_employee.flag == 'email'
		flash[:success] = 'Your Request has been sent'
		ShiftMailer.shift_notify(@shift, @user).deliver
		redirect_to :back
		elsif current_employee.flag == 'text_message'
		flash[:success] = 'Your Request has been sent'
		@shift_request = ShiftRequest.new
		@shift_request.user_num = @user.id
		@shift_request.shift_num = @shift.id
		@shift_request.save
		redirect_to :back
		else 
		redirect_to :back 
		end
  end
end

def accept
	if params[:true]
	@employee = Shift.find(params[:id])
	coworker = @employee.coworkers.match
	end
end


private 
def shift_params
params.require(:shift).permit(:shift_day,:start,:end,:position)
end

def check_if_allowed
	if Employee.where(id: params[:employee_id]).take.alert == 'yes'
		flash[:success] = "This user has stopped taking requests"
		redirect_to :back
	else
		return true  
	end 
end

end

app/helpers/shifts_helper.rb
module ShiftsHelper
  
  def index_for_options(list)
  list2 = list.dup
  list2.map!{|x| Array.new(1,x) << x} 
    count = 0
    while count < list2.length
      list2[count][1] = count + 1
      count += 1
    end
    return list2
  end 


  # arr = [[1,1], [2,2], [3,3], [4,4]]
  #arr[0][1]
  #arr[1][1] 
  #arr[2][1]
  #arr[3][1]
end

app/views/shifts/index.html.erb
<style>
  .selected { 
    background-color: #ff0000;
    }
</style>

<div class="container top">
<h1 class="col-xs-12 text-center">Bulletin</h1> 
<hr/>
<body>
<%if logged_in?%>

<p class="text-center">All available shifts</p> 

<div class="row">
<div>
<%=link_to 'Current', bulletin_path(:week => 1), method: :get, class: "btn btn-primary col-xs-3" %>
</div>
<div>
<%=link_to 'Next Week', bulletin_path(:week => 2), method: :get , class: "btn btn-primary col-xs-3" %>
</div>
<div>
<%=link_to 'Week 3', bulletin_path(:week => 3), method: :get, class: "btn btn-primary col-xs-3" %>
</div>
<div>
<%=link_to 'Week 4', bulletin_path(:week => 4), method: :get, class: "btn btn-primary col-xs-3" %>
</div>
</div>

</br>
<%=form_tag('/bulletin', method: :get) do %>
<% if @container%>
<div class="">
<%=select_tag( "day", options_for_select(@container))%>
</div>
</br>
<%=submit_tag "search", class: "btn btn-success btn-block"%>
<% else %>
<div class="">
<%= select_tag("day")%>
</div>
</br>
<%= submit_tag "search", class: "btn btn-success btn-block" %>
<%end %>
<%end%>

<h1>All Available Shifts</h1>
<h5>Today <%= Date.today.strftime("%B %d") %></h5>
<!-- Pressing the week shouldnt reset the days-->

<div id="total">
<p class="pull-right"> Total Shifts <span class="badge"><%= @shifts.count%></span></p>
</div>
 <ul>
		<% @shifts.each do |shift|%>
    <li>
      <div class="panel-heading"><h4><%= shift.employee.full_name%></h4></div>
      <div class="panel panel-default">
        <div class="panel-body">
  			   <%= shift.shift_day.strftime "%m/%d/%Y"%>
           <%= "#{shift.start.strftime("%I:%M%P")} - #{shift.end.strftime(" %I:%M%P")}"%>
        <div class="panel-footer"> 
        <%if shift.employee_id != current_employee.id %>
        <%=button_to "Request", notify_employee_shift_path(shift.employee_id, shift.id)%>
        <%else%>
          Shift Not Available
        <%end%>  
        </div>
       </div>
      </div>
    </li>
		<%end%> 	
<%end%>
</ul>
  <%= will_paginate @shifts, renderer: BootstrapPagination::Rails%>
</div>




</body>

app/views/shifts/new.html.erb
<h1 class="text-center"> Add A Shift</h1>
<div class=" well">
<%= form_for [@employee, @shift] do |f|%>
  <div class="field">
    <%=f.label :Date, class: "text-center"%>:
    <%=f.date_select :shift_day%>
  </div>
  <div class="field ">
    <%= f.label 'Start time'%>:
    <%= f.time_select :start, {:ampm => true}%>
  </div>
  <div class="field">
    <%= f.label 'End time'%>: 
    <%= f.time_select :end , {:ampm => true}%>
  </div>
  <div class="field ">
    <%= f.label 'Position', class: "text-center"%>: 
    <%= f.text_field :position, placeholder: "eg: 2nd Flr Stock "%>
  </div>
</br>
  <div class="actions">
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <i class="glyphicon glyphicon-send"> Send</i>
    <%end%>
  </div>
<% end %>
</div>

<!--url: employee_shift_path -->