config/routes.rb
Rails.application.routes.draw do
 
 resources :employees, except: [:new] do
 post '/message_choice', to: 'employees#message_choice' 
 post '/stop_request', to: 'employees#stop_request'
 resources :shifts do
 member do
 	post 'notify'
  post 'accept'
 end
end
end
get '/register', to: 'employees#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
get 'bulletin', to: 'shifts#index', as: :bulletin
############### Constraints for the top routes 
get '/acccounts', to: 'accounts#new', as: :sign_up
post '/accounts', to: 'accounts#create', as: :accounts



root to: 'dashboard#index', as: '/dashboard'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adjust</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
   <style>
    body { padding-top: 70px;}
  </style>
</head>

<body> 

  <!-- NavBar  -->
<div class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'SHIFTLIST.CO', dashboard_path, class: "navbar-brand" %>
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>
        <div class="collapse navbar-collapse navHeaderCollapse">
          <ul class="nav navbar-nav navbar-right ">  
            <%if logged_in?%>
            <li><%= link_to 'Logout', logout_path%></li>
            <li><%= link_to 'Manage Profile', employee_path(current_employee)%></li>
            <%else%>
             <li><%=link_to 'Log In', login_path%></li>
             <li><%=link_to 'Demo', register_path%></li>
            <%end%>
          </ul>
      </div>
  </div>
</div>

<!-- navbar-right -->
<!-- Flash Alert -->
<% flash.each do |type, message| %>
  <div class="alert alert-<%=type%> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

<%= yield %>

<script src="https://code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js" />
<%= javascript_include_tag( :application) %>

</body>
</html>